#!/usr/bin/env bash

echo "===SAM deploy==="

STACK_NAME="calendar-notification"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region ap-northeast-3 \
--stack-name $STACK_NAME